version: '3'

services:
  server:
    container_name: server-node02
    image: node
    ports:
      - 3000:3000
    volumes:
      - ./src:/src
    working_dir: '/src'
    command: 'sh start.sh'

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./static:/static
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
