version: "3"
services:
  lab01:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
      - "9222:9222"
    tty: true
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./static:/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
