version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  server:
    build: ./node
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
      - "9222:9222"
    tty: true
    links:
      - redis
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./static:/static
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf


