version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hw-5-database
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  node-app:
    build: ./node
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
      - "9222:9222"
    tty: true
    depends_on:
      - postgres
      - redis
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./static:/static
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  redis:
    image: redis
    ports:
      - "6379:6379"

